name: zdrowerasowe_v1
description: Zdrowe Rasowe
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.14
  get: ^4.6.5
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.2
  font_awesome_flutter: ^10.5.0
  dio: ^5.3.2

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: "assets/launcher-logo-apple.png"
  image: "assets/launcher-logo-apple.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
#
#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/zr-bez-tla.png"
#  adaptive_icon_background: '#FFFFF'
#  adaptive_icon_foreground: "assets/zr-bez-tla.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - "assets/zr-bez-tla.png"
    - "assets/pies1.jpg"
    - "assets/pies2.jpg"
    - "assets/pies3.jpg"
    - "assets/pies4.png"
    - "assets/pies5.jpg"
    - "assets/psy1.png"
    - "assets/psy2.jpg"
    - "assets/szczeniak1.png"
    - "assets/kastrujemy.jpg"
    - "assets/lapa1.png"
    - "assets/lapa2.png"
    - "assets/lapa3.png"
    - "assets/lapa4.png"
    - "assets/lapa5.png"
    - "assets/lapa6.png"
    - "assets/kot-linia.png"
    - "assets/kot-pies3.png"
    - "assets/warning.png"
    - "assets/facebook.png"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
